# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models
import apps.assets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('asset_type', models.CharField(choices=[('Generic', 'Generic'), ('Site', 'Site'), ('Workshop', 'Workshop'), ('BOILER', 'Boiler'), ('DEAERATOR', 'Deaerator'), ('Steam trap', 'Steam Trap'), ('Heat exchanger', 'Heat Ex'), ('Heating package', 'Heat Package'), ('Control valve', 'Control Valve'), ('PRS', 'Prs'), ('Safety valve', 'Safety Valve'), ('Mechanical pump', 'Mech Pump'), ('Mechanical pump CRU', 'Mech Pump Cru'), ('Electrical pump', 'El Pump'), ('Electrical pump CRU', 'El Pump Cru')], default='Generic')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=None, null=True)),
                ('curr_state', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=None, null=True)),
                ('last_status_update_ts', models.BigIntegerField(blank=True, default=None, null=True)),
                ('last_curr_state_update_ts', models.BigIntegerField(blank=True, default=None, null=True)),
                ('status_use', models.IntegerField(choices=[(0, 'Dont Use'), (1, 'As Is'), (2, 'As Warning'), (3, 'As Error If All')], default=2)),
                ('curr_state_use', models.IntegerField(choices=[(0, 'Dont Use'), (1, 'As Is'), (2, 'As Warning'), (3, 'As Error If All')], default=2)),
                ('health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('next_upd_ts', models.BigIntegerField(default=0)),
                ('reeval_fields', models.JSONField(blank=True, default=apps.assets.models.get_reeval_fields)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', related_query_name='asset', to='assets.asset')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
    ]
