# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datatypes', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_rbe', models.BooleanField(default=False)),
                ('time_update', models.BigIntegerField(blank=True, default=None, null=True)),
                ('time_change', models.BigIntegerField(blank=True, default=None, null=True)),
                ('till_now_margin', models.BigIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=dict)),
                ('health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('msg_health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('nd_health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('time_nd_health_error', models.BigIntegerField(default=300000)),
                ('health_next_eval_ts', models.BigIntegerField(default=0)),
                ('max_rate_of_change', models.FloatField(default=1.0)),
                ('max_plausible_value', models.FloatField(default=1000000.0)),
                ('min_plausible_value', models.FloatField(default=-1000000.0)),
                ('ts_to_start_with', models.BigIntegerField(default=0)),
                ('last_valid_reading_ts', models.BigIntegerField(blank=True, default=None, null=True)),
                ('created_ts', models.BigIntegerField(editable=False)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dt_datastreams', related_query_name='dt_datastream', to='datatypes.datatype')),
                ('meas_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to='datatypes.measunit')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', related_query_name='datastream', to='devices.device')),
            ],
            options={
                'db_table': 'datastreams',
                'constraints': [models.UniqueConstraint(fields=('name', 'parent_id'), name='unique_name_device')],
            },
        ),
    ]
