# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('datastreams', '0001_initial'),
        ('datatypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datafeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('df_type', models.CharField(choices=[('None', 'None'), ('Status', 'Status'), ('Current state', 'Current State'), ('State', 'State'), ('Steam loss', 'Steam Loss'), ('Water loss', 'Water Loss'), ('Energy loss', 'Energy Loss'), ('Steam savings', 'Steam Savings'), ('Water savings', 'Water Savings'), ('Energy savings', 'Energy Savings')], default='None')),
                ('is_rest_on', models.BooleanField(default=True)),
                ('is_aug_on', models.BooleanField(default=True)),
                ('aug_policy', models.IntegerField(choices=[(1, 'Till Last Df Reading'), (2, 'Till Now')], default=1)),
                ('ts_to_start_with', models.BigIntegerField(default=0)),
                ('last_reading_ts', models.BigIntegerField(blank=True, default=None, null=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dt_datafeeds', related_query_name='dt_datafeed', to='datatypes.datatype')),
                ('datastream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafeeds', related_query_name='datafeed', to='datastreams.datastream')),
                ('meas_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to='datatypes.measunit')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafeeds', related_query_name='datafeed', to='applications.application')),
            ],
            options={
                'db_table': 'datafeeds',
                'constraints': [models.UniqueConstraint(fields=('name', 'parent_id'), name='unique_name_app')],
            },
        ),
    ]
