# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dev_ui', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=dict)),
                ('health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('chld_health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('msg_health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('next_upd_ts', models.BigIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', related_query_name='device', to='assets.asset')),
            ],
            options={
                'db_table': 'devices',
                'indexes': [models.Index(fields=['dev_ui'], name='dev_ui_idx')],
            },
        ),
    ]
