# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


additional_operations = []
if settings.DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    additional_operations = [
        migrations.RunSQL(
            """
            SELECT create_hypertable('df_readings', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE df_readings;
            """,
        ),
    ]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datafeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfReading',
            fields=[
                ('pk', models.CompositePrimaryKey('datafeed_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('db_value', models.FloatField()),
                ('restored', models.BooleanField(default=False)),
                ('datafeed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datafeeds.datafeed')),
            ],
            options={
                'db_table': 'df_readings',
            },
        ),
        *additional_operations,
    ]
