# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


additional_operations = []
if settings.DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    additional_operations = [
        migrations.RunSQL(
            """
            SELECT create_hypertable('ds_readings', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE ds_readings;
            """,
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('invalid_ds_readings', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE invalid_ds_readings;
            """,
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('nd_markers', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE nd_markers;
            """,
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('nonroc_ds_readings', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE nonroc_ds_readings;
            """,
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('unused_ds_readings', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE unused_ds_readings;
            """,
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('unused_nd_markers', by_range('time', 86400000));
            """,
            reverse_sql="""
                DROP TABLE unused_nd_markers;
            """,
        ),
    ]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datastreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsReading',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('db_value', models.FloatField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'ds_readings',
            },
        ),
        migrations.CreateModel(
            name='InvalidDsReading',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('db_value', models.FloatField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'invalid_ds_readings',
            },
        ),
        migrations.CreateModel(
            name='NoDataMarker',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'nd_markers',
            },
        ),
        migrations.CreateModel(
            name='NonRocDsReading',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('db_value', models.FloatField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'nonroc_ds_readings',
            },
        ),
        migrations.CreateModel(
            name='UnusedDsReading',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('db_value', models.FloatField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'unused_ds_readings',
            },
        ),
        migrations.CreateModel(
            name='UnusedNoDataMarker',
            fields=[
                ('pk', models.CompositePrimaryKey('datastream_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'unused_nd_markers',
            },
        ),
        *additional_operations,
    ]
