# Generated by Django 5.2 on 2025-10-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Temperature', max_length=200, unique=True)),
                ('agg_type', models.IntegerField(choices=[(0, 'Avg'), (1, 'Sum'), (2, 'Last')], default=0)),
                ('var_type', models.IntegerField(choices=[(0, 'Continuous'), (1, 'Discrete'), (3, 'Nominal'), (4, 'Ordinal')], default=0)),
                ('is_totalizer', models.BooleanField(default=False)),
                ('category_map', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'datatypes',
            },
        ),
        migrations.CreateModel(
            name='MeasUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('symbol', models.CharField(max_length=15)),
                ('k', models.FloatField(default=1.0)),
                ('b', models.FloatField(default=0.0)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dt_measunits', related_query_name='dt_measunit', to='datatypes.datatype')),
            ],
            options={
                'db_table': 'measunits',
            },
        ),
    ]
